name: Create Release (Simple)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Check code style
      run: vendor/bin/pint --test

    - name: Create Release with GitHub CLI
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        
        # Create release using GitHub CLI
        gh release create $VERSION \
          --title "Release $VERSION" \
          --notes "## What's Changed
        
        This release includes all the latest features and improvements for Laravel FeatureBox.
        
        ### Features
        - Feature toggle functionality with database storage
        - JSON-based conditions support
        - Environment-based conditions
        - User role and ID-based conditions
        - Date range conditions
        - Custom conditions support
        - Artisan commands for feature management
        - Caching support for performance
        
        ### Documentation
        - Comprehensive API documentation
        - Multi-language support (English & Arabic)
        - Advanced usage examples
        
        ### Testing
        - 12 comprehensive tests with 100% pass rate
        - Full test coverage for all functionality
        
        ### Performance
        - Built-in caching with configurable TTL
        - Optimized database queries
        - Efficient condition evaluation
        
        ## Installation
        
        \`\`\`bash
        composer require mohamedhekal/laravel-featurebox
        \`\`\`
        
        ## Quick Start
        
        \`\`\`bash
        php artisan vendor:publish --tag=featurebox-config
        php artisan vendor:publish --tag=featurebox-migrations
        php artisan migrate
        php artisan featurebox:enable new_feature
        \`\`\`
        
        ## Usage
        
        \`\`\`php
        use FeatureBox\Facades\FeatureBox;
        
        if (FeatureBox::isEnabled('new_feature')) {
            // New feature logic
        }
        \`\`\`
        
        For more information, see the [documentation](https://github.com/mohamedhekal/laravel-featurebox#readme)." \
          --draft=false \
          --prerelease=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 